

import Foundation

struct AnimalFact: Identifiable {
    let id = UUID()
    let text: String
    let category: AnimalCategory?
    
    static let sampleFacts: [AnimalFact] = [
        AnimalFact(text: "Elephants can recognize themselves in a mirror — a sign of self-awareness.", category: AnimalCategory.animal),
        AnimalFact(text: "Lions sleep up to 20 hours a day.", category: .animal),
        AnimalFact(text: "Pandas eat up to 14 hours a day, consuming about 20 kg of bamboo.", category: .animal),
        AnimalFact(text: "Dolphins have names for each other and can recognize themselves in mirrors.", category: .animal),
        AnimalFact(text: "A group of lions is called a pride, and a group of elephants is called a herd.", category: .animal),
        AnimalFact(text: "Tigers have unique stripe patterns, just like human fingerprints.", category: .animal),
        AnimalFact(text: "Wolves can run at speeds of up to 65 km/h when hunting.", category: .animal),
        AnimalFact(text: "Bears can run as fast as horses for short distances.", category: .animal),
        AnimalFact(text: "Foxes have excellent hearing and can detect the squeak of a mouse from 30 meters away.", category: .animal),
        AnimalFact(text: "Cats have 32 muscles in each ear, allowing them to rotate their ears 180 degrees.", category: .animal),
        AnimalFact(text: "Dogs can understand up to 250 words and gestures, making them as intelligent as a 2-year-old child.", category: .animal),
        AnimalFact(text: "Horses can sleep both standing up and lying down.", category: .animal),
        AnimalFact(text: "Pigs are one of the smartest animals and can learn tricks faster than dogs.", category: .animal),
        AnimalFact(text: "Cows have best friends and become stressed when separated from them.", category: .animal),
        AnimalFact(text: "Goats have rectangular pupils, giving them excellent peripheral vision.", category: .animal),
        AnimalFact(text: "Hedgehogs can have up to 7,000 spines on their backs.", category: .animal),
        AnimalFact(text: "Jaguars are excellent swimmers and often hunt in water.", category: .animal),
        AnimalFact(text: "A tiger's roar can be heard from up to 3 kilometers away.", category: .animal),
        AnimalFact(text: "Elephants can communicate using infrasound, which humans cannot hear.", category: .animal),
        AnimalFact(text: "Lions are the only cats that live in groups called prides.", category: .animal),
        
        AnimalFact(text: "Eagles can see prey from a distance of up to 3 kilometers.", category: .bird),
        AnimalFact(text: "Owls can turn their heads 270 degrees.", category: .bird),
        AnimalFact(text: "Penguins can dive to depths of up to 500 meters.", category: .bird),
        AnimalFact(text: "Parrots can live for over 80 years, making them one of the longest-living birds.", category: .bird),
        AnimalFact(text: "Ducks have waterproof feathers thanks to special oil they produce.", category: .bird),
        AnimalFact(text: "Peacocks can fly, despite their large and heavy tail feathers.", category: .bird),
        AnimalFact(text: "Chickens can remember over 100 different faces of people and animals.", category: .bird),
        AnimalFact(text: "Crows are among the smartest birds and can use tools to solve problems.", category: .bird),
        AnimalFact(text: "Geese fly in a V-formation to reduce wind resistance and save energy.", category: .bird),
        AnimalFact(text: "Owls have asymmetrical ears, which helps them locate prey by sound.", category: .bird),
        AnimalFact(text: "Penguins can drink saltwater because they have special glands to filter out salt.", category: .bird),
        AnimalFact(text: "Eagles can fly at speeds of up to 160 km/h when diving for prey.", category: .bird),
        AnimalFact(text: "Parrots have zygodactyl feet, meaning two toes point forward and two backward.", category: .bird),
        AnimalFact(text: "Ducks can sleep with one eye open to watch for predators.", category: .bird),
        AnimalFact(text: "A peacock's tail can be up to 60% of its total body length.", category: .bird),
        AnimalFact(text: "Chickens have over 30 distinct vocalizations to communicate different messages.", category: .bird),
        AnimalFact(text: "Crows can recognize human faces and hold grudges against people who have wronged them.", category: .bird),
        AnimalFact(text: "Geese mate for life and will mourn the loss of their partner.", category: .bird),
        
        AnimalFact(text: "Butterflies taste food with their feet — they have taste receptors on their legs.", category: .insect),
        AnimalFact(text: "Bees communicate with each other through dance.", category: .insect),
        AnimalFact(text: "Ants can lift weights 50 times their own body weight.", category: .insect),
        AnimalFact(text: "A bee's wings beat about 200 times per second, creating the buzzing sound.", category: .insect),
        AnimalFact(text: "Butterflies can see ultraviolet light, which helps them find flowers.", category: .insect),
        AnimalFact(text: "Ladybugs can eat up to 5,000 aphids in their lifetime.", category: .insect),
        AnimalFact(text: "Grasshoppers can jump 20 times their own body length.", category: .insect),
        AnimalFact(text: "Spiders produce silk that is stronger than steel of the same thickness.", category: .insect),
        AnimalFact(text: "Ant colonies can contain millions of individuals working together.", category: .insect),
        AnimalFact(text: "Bees have five eyes — two large compound eyes and three small simple eyes.", category: .insect),
        AnimalFact(text: "Butterflies migrate thousands of kilometers, with monarch butterflies traveling up to 4,800 km.", category: .insect),
        AnimalFact(text: "A single honeybee produces only about 1/12 of a teaspoon of honey in its lifetime.", category: .insect),
        AnimalFact(text: "Ladybugs can release a foul-smelling liquid from their legs when threatened.", category: .insect),
        AnimalFact(text: "Grasshoppers can make sounds by rubbing their legs against their wings.", category: .insect),
        AnimalFact(text: "Spiders can regenerate lost legs during molting.", category: .insect),
        AnimalFact(text: "Ants have been farming for millions of years, growing fungi for food.", category: .insect),
        AnimalFact(text: "Bees can recognize human faces and remember them for days.", category: .insect),
        AnimalFact(text: "Butterflies have a lifespan ranging from a week to nearly a year, depending on the species.", category: .insect),
        
        AnimalFact(text: "Sharks have existed on Earth for more than 400 million years.", category: .fish),
        AnimalFact(text: "Octopuses have three hearts and blue blood.", category: .fish),
        AnimalFact(text: "Fish can hear sounds underwater better than humans on land.", category: .fish),
        AnimalFact(text: "Sharks can detect a single drop of blood in 25 gallons of water.", category: .fish),
        AnimalFact(text: "Frogs can breathe through their skin when underwater.", category: .fish),
        AnimalFact(text: "Some fish can change their gender during their lifetime.", category: .fish),
        AnimalFact(text: "Sharks never stop swimming, as they need water flowing over their gills to breathe.", category: .fish),
        AnimalFact(text: "Octopuses have nine brains — one central brain and eight in their arms.", category: .fish),
        AnimalFact(text: "Fish can see colors that humans cannot perceive.", category: .fish),
        AnimalFact(text: "A shark's skin is covered in tiny scales called dermal denticles, making it feel like sandpaper.", category: .fish),
        AnimalFact(text: "Frogs can jump up to 20 times their own body length.", category: .fish),
        AnimalFact(text: "Some fish can produce electricity to stun their prey.", category: .fish),
        AnimalFact(text: "Sharks have been around longer than trees, dinosaurs, and even the rings of Saturn.", category: .fish),
        AnimalFact(text: "Octopuses can change color and texture to blend in with their surroundings in less than a second.", category: .fish),
        AnimalFact(text: "Fish have been on Earth for over 500 million years.", category: .fish),
        AnimalFact(text: "A great white shark can detect electrical fields as small as 5 billionths of a volt.", category: .fish),
        AnimalFact(text: "Frogs absorb water through their skin, so they never need to drink.", category: .fish),
        AnimalFact(text: "Some fish can walk on land using their fins.", category: .fish),
        
        AnimalFact(text: "Some animals can see ultraviolet light.", category: nil),
        AnimalFact(text: "The fastest land animal is the cheetah, reaching speeds of up to 120 km/h.", category: nil),
        AnimalFact(text: "Whales are the largest mammals on the planet.", category: nil),
        AnimalFact(text: "The blue whale is the largest animal that has ever lived on Earth.", category: nil),
        AnimalFact(text: "Animals use various methods to communicate, including sounds, scents, body language, and even electricity.", category: nil),
        AnimalFact(text: "Many animals have better senses than humans — dogs can smell 1,000 times better than us.", category: nil),
        AnimalFact(text: "Some animals can regenerate lost body parts, like starfish regrowing arms.", category: nil),
        AnimalFact(text: "The smallest mammal in the world is the bumblebee bat, weighing less than 2 grams.", category: nil),
        AnimalFact(text: "Animals have been domesticated by humans for over 15,000 years.", category: nil),
        AnimalFact(text: "Many animals migrate thousands of kilometers each year to find food and breeding grounds.", category: nil),
        AnimalFact(text: "Some animals can survive extreme conditions, like tardigrades that can survive in space.", category: nil),
        AnimalFact(text: "Animals play important roles in ecosystems, helping to pollinate plants and control populations.", category: nil),
        AnimalFact(text: "The oldest known animal on Earth is a Greenland shark, which can live over 400 years.", category: nil),
        AnimalFact(text: "Many animals have unique adaptations that help them survive in their environments.", category: nil),
        AnimalFact(text: "Animals can form friendships and social bonds, just like humans.", category: nil)
    ]
}

